version: '3.8'
services:
  database:
    build:
      context: ./pg-scripts
      dockerfile: db.Dockerfile
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=garage
      - POSTGRES_DB=garageDB
    ports:
      - 127.0.0.1:5441:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    networks:
      - garage_network
  garage_consumer:
    image: garage-sqs-consumer:latest
    environment:
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_REGION=$AWS_REGION
      - AWS_SQS_QUEUE_URL=$AWS_SQS_QUEUE_URL
      - DB_USER=garage
      - DB_PWD=123456
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=garageDB
    networks:
      - garage_network

networks:
  garage_network:
